# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/carson/Nextcloud/Documents/school/ECEN340/final_project/8-bit-console-clone-verilog/eight_bit_console/eight_bit_console.srcs/sources_1/ip/dsp_pc_counter/dsp_pc_counter.xci
# IP: The module: 'dsp_pc_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carson/Nextcloud/Documents/school/ECEN340/final_project/8-bit-console-clone-verilog/eight_bit_console/eight_bit_console.gen/sources_1/ip/dsp_pc_counter/dsp_pc_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_pc_counter'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/carson/Nextcloud/Documents/school/ECEN340/final_project/8-bit-console-clone-verilog/eight_bit_console/eight_bit_console.srcs/sources_1/ip/dsp_pc_counter/dsp_pc_counter.xci
# IP: The module: 'dsp_pc_counter' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/carson/Nextcloud/Documents/school/ECEN340/final_project/8-bit-console-clone-verilog/eight_bit_console/eight_bit_console.gen/sources_1/ip/dsp_pc_counter/dsp_pc_counter_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'dsp_pc_counter'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
